name = "TensorDSL"
uuid = "5ee316d7-7d97-4eea-8eff-9a91f716181b"
authors = ["Sohva <33163737+Sohva@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Revise = "2.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
